import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { useState } from 'react';



function Home({blogs}) {
const [blog, setBlog] = useState(blogs);
  return (
    <>
      <Head>
       <title>Coding Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
      <main className={styles.main}>
        <h1>&lt;CodeCraftHub/&gt;</h1> 
        <h3>Connecting Developers, Unleashing Ideas</h3>
      </main>
      <img className={styles.img} src="/home.img" alt="coding" width={157} height={158} />
      <content className={styles.content}>
        <h2>Popular Blogs</h2>
        <ul className={styles.bloglist}>
        {blog.slice(0,6).map((eachblog) => {
          return(
            <div className={styles.blogstyle}>
            <li key={eachblog.id} className={styles.blogtheme}>
            <h2 className={styles.title}>{eachblog.title}</h2>
            <p className={styles.content}>{eachblog.content.slice(0,400)}</p>
          </li>
          </div>
          )
        }
          
        )}
      </ul>
      </content>
      </div>
    </>
  )
}

export async function getServerSideProps() {
  // Fetch data from your API route
  const response = await fetch('https://blog-website-drab-eight.vercel.app/api/getblogs');
  const blogs = await response.json();

  // Pass the blog data as a prop
  return {
    props: {
      blogs,
    },
  };
}
export default Home;